export interface userModel {
  id: number,
  profilePhoto: string,
  firstName: string,
  lastName: string,
  email: string,
  phone: number,
  age: number,
  state: string,
  country: string,
  address: string,
  address1: string,
  address2: string,
  interest: string,
  newsletter: boolean,
}